[package]
name = "kg-js"
version = "0.1.0"
authors = ["jchlapinski <jakub.chlapinski@kodegenix.pl>"]
description = """
Wrapper for duktape JavaScript engine.
"""
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/kodegenix/kg-js"
edition = "2018"
build = "build.rs"

[workspace]

[dependencies]
kg-diag = "0.2.1"
kg-tree = "0.1.4"
kg-utils = "0.2.4"
log = "0.4.7"
lazy_static = "1.3.0"
bitflags = "1.1.0"
rlibc = "1.0.0"

[build-dependencies]
cc = { version = "1.0.38", features = ["parallel"] }
